language: node_js
node_js:
- stable
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
  - bower_components
  - scripts/vendor
env:
  global:
  - secure: d1sNnuwm5qpv0fRRUAtZJd6+Y94118zf0RbfwTJgcJZpAdo/pZK4GyvNPV8H0Kr+MkkKBAmTzmq4bQN49CDp7Lx/rH7+N3BSDR/p52SjCKTMmwWsJkCAX4lswVSAI7XjDBH2ywZXQtSGh5pZi72l/UsS5Vmsj7UrTIbEBOLyJcKJoAG8VBWUngt3L574ObMywjCzI0iWxmmAvVAzq25eNZvCCLzsTCXVFgJqJkc3kxA7XpgQ/pX8OpfQQJWpK3bs8u9mJ3wt8jndHN7KEIK1Lg6lr/XePapZAf8ZhegUUDgWSVI8iFl6yTgBCUcFVezMyjRodcGchV9bDGKm7lI5RNb12e8TVmNtKThQPzH6fLbI6uRibAD7FQ0HzLf6Ke9UEbR4l7XPiTpOfrAk19lUcZUxfVIU+A82tJEsHLH+TycURKmXq3Wvpqmtez+WHzS+fgB4SyOnRkR4kWKwn4uF+f9BC4rMd1f+s5mgEH/WC8VxbJeSPfZkiXmAnie7TpdK4ZBfEOy/qSQ1UkMhfsWVTH22CyzsmkGgbxwxy0Q1IoOXa0Z1yvtDqSixkR8rrl6qwVFL3oI3e5vQ/jLHFDQC+JkVXKCn1FReEjy2fEoXyI5rZ1Fy+cqK/U/Kyx2D7cQGShZ1cDjW27NpAFTADi5sHwATu9VI0yiIvFrAiEkiO7Q=
  - secure: MN9mVWwY+U4JdXLGb3wfPIEoQoTackkIkVimDPNJdU8fXulRtEI4x/7qnJATbuNcIzZNu1yYWQ0g6gwmbphJdFUj7ua3FChbZxr24/65Bv1irMGY0WHbvJXahaDW3x4IujC9Dy6HWPlphjmJhQqCfjPmHoEdNifAJNBqdqsDEZn75plY+LI7CyPkbZ85+GucbuInRQq5fd+gOxpgSYjU0VtZxtUQAJh8SNfIuMPFrgVCM/wwLf1ksF/MI9zfv8mJ/GUNhxWcK4/eWSMo9VmTnWSh+s5PGLGfw9DoFCLzkJIqeyZ7MSBNoSxRtlGthhTO3veOaVZS+ZmgcxaSEIGhKeeh4prxVd2hVRhB1q3O0ch9Z76FUbh/KzVZGo7Sp0px6dnQ9+JJscFOHvBOtZ/SMAUAnCZYaeYZryutssMzZYxPP4+BB0qAaUtHAdjXy4i/NGPRjN2BbjwpUA+LMJiujxLq/etW1XLtGsvAQmE4D7e36zYD5KdJ0iq1sqp9VJs7EiFu0KXdB48xEZdXHDNj4WaCVHEmAUlrG9O5PzQfJyotDW/exIgN5U0C0pGHlL+6a3tGIPpdn13sfrAC47VoGzKd3Dnch9rQIOs+osruPgaRerhFePnvR0vjrZHQX27snGctIpE4foDOehDO85XnoRRavGB/KTjP2f5S7xqfzR8=
  - CHAISE_BASE_URL: https://dev.misd.isi.edu/chaise
